INSERT INTO `role` (`CODE_ROLE`, `LIBELLE_ROLE`) VALUES ('1', 'ADMINISTRATEUR');
INSERT INTO `role` (`CODE_ROLE`, `LIBELLE_ROLE`) VALUES ('2', 'AGENT DE FORMULATION');
INSERT INTO `role` (`CODE_ROLE`, `LIBELLE_ROLE`) VALUES ('3', 'CHEF DE FORMULATION');
INSERT INTO `role` (`CODE_ROLE`, `LIBELLE_ROLE`) VALUES ('4', 'AGENT D\'EXPLOITATION');
INSERT INTO `role` (`CODE_ROLE`, `LIBELLE_ROLE`) VALUES ('5', 'CHEF D\'EXPLOITATION');