CREATE USER 'U_ADMINISTRATEUR'@'localhost' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON BRAC_USERS . * TO 'U_ADMINISTRATEUR'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'U_ADMINISTRATEUR'@'localhost';