CREATE USER 'ADMINISTRATEUR'@'localhost' IDENTIFIED BY '1234';
CREATE USER 'AGENT_DE_FORMULATION'@'localhost' IDENTIFIED BY '1234';
CREATE USER 'CHEF_DE_FORMULATION'@'localhost' IDENTIFIED BY '1234';
CREATE USER 'AGENT_D\'EXPLOITATION'@'localhost' IDENTIFIED BY '1234';
CREATE USER 'CHEF_D\'EXPLOITATION'@'localhost' IDENTIFIED BY '1234';


GRANT ALL PRIVILEGES ON BRAC . * TO 'ADMINISTRATEUR'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'ADMINISTRATEUR'@'localhost';

GRANT SELECT ON BRAC . * TO 'CHEF_DE_FORMULATION'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'CHEF_DE_FORMULATION'@'localhost';

GRANT SELECT ON BRAC . * TO 'CHEF_D\'EXPLOITATION'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'CHEF_D\'EXPLOITATION'@'localhost';

GRANT SELECT,INSERT,UPDATE ON BRAC . * TO 'AGENT_DE_FORMULATION'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'AGENT_DE_FORMULATION'@'localhost';

GRANT SELECT,INSERT,UPDATE ON BRAC . * TO 'AGENT_D\'EXPLOITATION'@'localhost';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'AGENT_D\'EXPLOITATION'@'localhost';